LabImages:

<LabImages>:
    cols: 3
    rows: 1
    Image:
        source: "../resources/1_THE_LAB/RESOURCES/images/cake.jpg"
        size: self.texture.size
    Image:
        source: "../resources/1_THE_LAB/RESOURCES/images/lab_logo.png"
        size: self.texture.size
    Image:
        source: "../resources/1_THE_LAB/RESOURCES/images/lab_separator.png"
        size: self.texture.size

<LabCounterGridLayout>:
    cols: 3
    rows: 3

    ToggleButton:
        text: root.state_str
        on_state: root.execute_toggle_button_behaviour(self)
        size_hint: None, 1
        width: "100sp"

    # Label:
      #   text: root.state_str
      #   font_name: "../resources/1_THE_LAB/RESOURCES/fonts/Lcd.ttf"
      #   font_size: "20sp"
      #   color: 1, .5, .25, 1

    Button:
        text: "Click me to increment the counter"
        on_press: root.increment_counter()
        disabled: root.enable_button
    Label:
        text: f"Counter: {root.counter_int}"
        font_name: "../resources/1_THE_LAB/RESOURCES/fonts/Lcd.ttf"
        font_size: "60sp"
        color: 1, .5, .25, 1

    Switch:
        id: switch
        active: True
        size_hint: None, 1
        width: "100sp"

    Slider:
        id: slider
        min: 0
        value: 50
        max: 100
        step: 1
        value_track: True
        orientation: "horizontal"
        disabled: not switch.active
    BoxLayout:
        orientation: "vertical"
        Label:
            text: f"Slider Value: {int(slider.value)}"
            font_name: "../resources/1_THE_LAB/RESOURCES/fonts/Lcd.ttf"
            font_size: "20sp"
            color: 1, .5, .25, 1
        ProgressBar:
            id: progress_bar
            max: 100
            size_hint: None, 1
            width: "300sp"
            value: int(slider.value)

    TextInput:
        id: user_input_text
        text: "foo"
        multiline: False
        size_hint: None, 1
        width: "100sp"
        on_text_validate: root.on_text_validate(self)

    Label:
        text: root.validated_input_text_str
        font_name: "../resources/1_THE_LAB/RESOURCES/fonts/Lcd.ttf"
        font_size: "20sp"
        color: 1, .5, .25, 1
        # size_hint: None, 1
        # width: "100sp"


    # Button:
      #   text: "Click me get a random value"
      #   on_press: root.get_random_float_value()
    # Label:
      #   text: f"Counter {round(root.random_float, 2)}"
      #   font_name: "../resources/1_THE_LAB/RESOURCES/fonts/Lcd.ttf"
      #   font_size: "60sp"
      #   color: 1, .5, .25, 1



# <LabPageLayout@PageLayout>:
    # LabWidget:
    # LabBoxLayout:
    # LabAnchorLayout:

# <LabScrollView@ScrollView>:
    # LabStackLayout:
        # size_hint: 1, None
        #  height: self.minimum_height

# <LabStackLayout>:
    # Button:
      #   text: "A"
      #   size_hint: .2, .1
    # Button:
      #   text: "B"
      #   size_hint: .2, .1
    # Button:
      #   text: "C"
      #   size_hint: .2, .1

<LabGridLayout@GridLayout>:
    # cols: 3
    rows: 2
    Button:
        text: "This is button 1"
        size_hint: .2, .1
    LabBoxLayout:
    Button:
        text: "This is button 3"
    Button:
        text: "This is button 4"
    Button:
        text: "This is button 5"
    Button:
        text: "This is button 6"

<LabAnchorLayout>:

    anchor_x: "center"
    anchor_y: "top"

    BoxLayout:
        size_hint: .25, .1
        orientation: "vertical"
        Button:
            text: "This is button 1"
        Button:
            text: "This is button 1"


<LabBoxLayout>:
    orientation: "horizontal"
    Button:
        text:
            "This is button 1"
        # size: "200sp", "50sp"
        # pos: "100dp", "100dp"
        size_hint: .5, None
        width: "50sp"
        pos_hint: {"center_y": .5}
        color: 0, 0, 1, 1
        background_color: 1, 0, 0, 1
    BoxLayout:
        orientation: "vertical"
        spacing: "100sp"
        Button:
            text:
                "This is button 2"
            size_hint: .8, 2.
            color: 1, 0, 0, 1
            background_color: 0, 0, 1, 1
        Button:
            text:
                "This is button 3"
            size_hint: .8, 2.
            color: 1, 0, 0, 1
            background_color: 0, 0, 1, 1
        Button:
            text:
                "This is button 4"
            size_hint: .8, 2.
            color: 1, 0, 0, 1
            background_color: 0, 0, 1, 1
        Button:
            text:
                "This is button 5"
            size_hint: .8, 2.
            color: 1, 0, 0, 1
            background_color: 0, 0, 1, 1

<LabWidget>:
    Button:
        text:
            "This is button 1"
        size: "200sp", "50sp"
        pos: "100dp", "100dp"
        color: 0, 0, 1, 1
    Label:
        text:
            "This is button 2"
        size: "200sp", "50sp"
        pos: "200dp", "200dp"
        color: 1, 0, 0, 1
